apiVersion: skaffold/v4beta11
kind: Config

build:
  artifacts:
    - image: my-node-app
      context: ./service23
      docker:
        dockerfile: Dockerfile
    - image: second-app23
      context: ./service24
      docker:
        dockerfile: Dockerfile

manifests:
  helm:
    releases:
      - name: node-release-babai23
        chartPath: charts/my-app
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_my_node_app}}"
          image.tag: "{{.IMAGE_TAG_my_node_app}}"
      - name: second-app23-release24
        chartPath: charts/second-app23
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_second_app23}}"
          image.tag: "{{.IMAGE_TAG_second_app23}}"

deploy:
  helm: {}      # Tells Skaffold to use the Helm deployer for the manifests defined above

################ istio vaddu anukunte, ee block comment cheyyii ###############################
---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: istio-routing

manifests:              # --- Module 2: Render and Deploy Istio Raw YAMLs ---
  rawYaml:
    - charts/istio-routing.yaml
deploy:
  kubectl: {} # Tells Skaffold to use standard kubectl to apply the raw manifests

################ istio vaddu anukunte, ee block comment cheyyii ###############################

portForward:
  - resourceType: service
    resourceName: node-app-service-babu23
    port: 80
    localPort: 13023

  - resourceType: service
    resourceName: second-app-service-url23
    port: 4044
    localPort: 14044