apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}

spec:

  # replicas: 1
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.service.name }}
    
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
        - name: webserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          env:
            ################ POD IP ======== later23
            # - name: POD_IP23
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: status.podIp

            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DB_USER
              value: {{ .Values.database.user | quote }}
        #   - name: DB_PASSWORD
        #     value: {{ .Values.database.password | quote }}

          ports:
            - containerPort: {{ .Values.service.targetPort24 }}